# Generated by Django 3.0.6 on 2020-05-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('site_content', models.TextField()),
                ('site_published', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
