# Generated by Django 3.0.7 on 2020-06-07 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podder_title', models.CharField(max_length=200)),
                ('podder_description', models.TextField()),
                ('podder_published', models.DateTimeField(default=datetime.datetime(2020, 6, 7, 22, 28, 59, 680889, tzinfo=utc), verbose_name='Date Published')),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 22, 28, 59, 680662, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
