# Generated by Django 3.0.7 on 2020-06-07 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200607_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='podder',
            name='podder_audio',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 22, 37, 3, 743972, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 22, 37, 3, 743728, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
