# Generated by Django 3.0.7 on 2020-06-08 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200608_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podder',
            name='podder_audio',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 21, 34, 7, 803258, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 21, 34, 7, 803026, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
