# Generated by Django 3.0.8 on 2020-07-03 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200611_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume',
            new_name='resume_data',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_category',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 17, 15, 16, 880961, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 17, 15, 16, 880658, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
