# Generated by Django 3.0.8 on 2020-08-11 01:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200703_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_description', models.TextField()),
                ('blog_post', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 1, 14, 54, 764799, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 1, 14, 54, 764465, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
