# Generated by Django 3.0.8 on 2020-08-11 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200811_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 1, 23, 0, 856529, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 1, 23, 0, 856222, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
