# Generated by Django 3.0.8 on 2020-08-11 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200811_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 1, 32, 3, 16281, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 1, 32, 3, 15928, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
