# Generated by Django 3.0.8 on 2020-08-11 02:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200811_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 2, 30, 45, 304316, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 2, 30, 45, 303993, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
