# Generated by Django 3.1 on 2020-11-19 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201119_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 3, 41, 20, 756947, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 3, 41, 20, 756278, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
