# Generated by Django 3.0.8 on 2021-09-30 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201119_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_title', models.CharField(max_length=200)),
                ('podcast_description', models.TextField()),
                ('podder_cover_art', models.FileField(upload_to='images')),
                ('podcast_url', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 1, 47, 24, 50724, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 1, 47, 24, 50416, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
