# Generated by Django 3.0.8 on 2021-09-30 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210930_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='podcast_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 2, 48, 32, 865014, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 2, 48, 32, 864605, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
