# Generated by Django 4.1.2 on 2022-10-16 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210930_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 23, 41, 40, 516024, tzinfo=datetime.timezone.utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 23, 41, 40, 515732, tzinfo=datetime.timezone.utc), verbose_name='Date Published'),
        ),
    ]
