# Generated by Django 4.1.2 on 2022-10-17 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_podder_podder_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 0, 42, 36, 803411, tzinfo=datetime.timezone.utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 0, 42, 36, 803126, tzinfo=datetime.timezone.utc), verbose_name='Date Published'),
        ),
    ]
