# Generated by Django 4.1.2 on 2022-10-17 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_podder_podder_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podder',
            name='podder_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 0, 44, 53, 781685, tzinfo=datetime.timezone.utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 0, 44, 53, 781388, tzinfo=datetime.timezone.utc), verbose_name='Date Published'),
        ),
    ]
