# Generated by Django 4.1.2 on 2022-10-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='volume_numer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
