# Generated by Django 4.1.2 on 2022-10-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_library', '0002_manga_volume_numer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='volume_numer',
            new_name='volume_number',
        ),
    ]
